msrv = "1.58"
blacklisted-names = ["foo", "baz", "quux"]
avoid-breaking-exported-api = true
too-large-for-stack = 200
cognitive-complexity-threshold = 20
literal-representation-threshold = 16384
disallowed-methods = []
allowed-scripts = ["Latin"]
disallowed-types = []
doc-valid-idents = ["KiB", "MiB", "GiB", "TiB", "PiB", "EiB", "DirectX", "ECMAScript", "GPLv2", "GPLv3", "GitHub", "GitLab", "IPv4", "IPv6", "ClojureScript", "CoffeeScript", "JavaScript", "PureScript", "TypeScript", "NaN", "NaNs", "OAuth", "GraphQL", "OCaml", "OpenGL", "OpenMP", "OpenSSH", "OpenSSL", "OpenStreetMap", "OpenDNS", "WebGL", "TensorFlow", "TrueType", "iOS", "macOS", "FreeBSD", "TeX", "LaTeX", "BibTeX", "BibLaTeX", "MinGW", "CamelCase"]
enum-variant-name-threshold = 3
max-fn-params-bools = 2
max-suggested-slice-pattern-length = 3
array-size-threshold = 512000
enum-variant-size-threshold = 200
single-char-binding-names-threshold = 0
enforced-import-renames = []
enable-raw-pointer-heuristic-for-send = true
standard-macro-braces = []
max-struct-bools = 3
too-many-arguments-threshold = 7
too-many-lines-threshold = 100
type-complexity-threshold = 250
max-trait-bounds = 3
unreadable-literal-lint-fractions = true
upper-case-acronyms-aggressive = false
vec-box-size-threshold = 4096
verbose-bit-mask-threshold = 1
warn-on-all-wildcard-imports = true
