disable_all_formatting = false
edition = "2021"
fn_args_layout = "Tall"
force_explicit_abi = true
hard_tabs = false
match_arm_leading_pipes = "Always"
match_block_trailing_comma = true
max_width = 120
merge_derives = true
newline_style = "Unix"
remove_nested_parens = true
reorder_imports = true
tab_spaces = 2
use_field_init_shorthand = true
use_small_heuristics = "Max"
use_try_shorthand = true
